# Generated by Django 3.2.7 on 2021-09-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('imdb', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('actor_id', models.ManyToManyField(to='film.Actor')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='movie_id',
            field=models.ManyToManyField(to='film.Movie'),
        ),
    ]
